services:
  scanxtract-engine:
    image: scanxtract:latest
    build: .
    container_name: scanxtract-engine
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
      
    restart: unless-stopped

volumes:
  uploads_data:    