version: '3.8'

services:
  scanxtract-engine:
    image: scanxtract
    build: .
    container_name: scanxtract-engine
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped